name: JUCE Private Trigger
on: [push]
jobs:
  trigger:
    if: github.repository == 'juce-framework/JUCE-tmp'
    runs-on: ubuntu-latest
    steps:
      - uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: JUCE Private Build

