name: JUCE Private Trigger
on: [push]
jobs:
  trigger:
    if: github.repository == 'juce-framework/JUCE-tmp'
    uses: peter-evans/repository-dispatch@v3
    with:
      workflow: JUCE Private Build
      event-type: my-event

